package M3;

/**
 *
 * @author Augusto
 */
public enum m3LanguageProperty {
    ADD_ELEMENT_ICON,
    
    ADD_LINE_TOOLTIP,
    ADD_STATION_TOOLTIP,
    
    REMOVE_ELEMENT_ICON,
    REMOVE_ELEMENT_TOOLTIP,
    
    REMOVE_STATION_TOOLTIP,
    REMOVE_LINE_TOOLTIP,
    
    LIST_ICON,
    LIST_TOOLTIP,
    
    ROUTE_ICON,
    ROUTE_TOOLTIP,
    
    BOLD_ICON,
    BOLD_TOOLTIP,
    
    ITALIC_ICON,
    ITALIC_TOOLTIP,
    
    ZOOM_IN_ICON,
    ZOOM_IN_TOOLTIP,
    ZOOM_OUT_ICON,
    ZOOM_OUT_TOOLTIP,
    
    EXPAND_MAP_ICON,
    EXPAND_MAP_TOOLTIP,
    MINIMIZE_MAP_ICON,
    MINIMIZE_MAP_TOOLTIP,
    
    ROTATE_LABEL_ICON,
    ROTATE_LABEL_TOOLTIP,
    
    EDIT_LINE_TOOLTIP,
    EDIT_STATION_TOOLTIP,
    ADD_STATION_TO_LINE_TOOLTIP,
    REMOVE_STATION_FROM_LINE_TOOLTIP,
    SNAP_STATION_TOOLTIP,
    MOVE_LABEL_TOOLTIP,
    
    SET_BACKGROUND_TOOLTIP,
    SET_IMAGE_BACKGROUND_TOOLTIP,
    ADD_IMAGE_TOOLTIP,
    ADD_LABEL_TOOLTIP,
    TEXT_COLOR_TOOLTIP
    
}